myproject/core/urls.py
from django.conf.urls import url
from myproject.core import views as c

urlpatterns = [
    url(r'^$', c.home, name='home'),
    url(r'^movie/$', c.MovieList.as_view(), name='movie_list'),
    url(r'^movie/(?P<pk>\d+)/$', c.MovieDetail.as_view(), name='movie_detail'),
    url(r'^movie/add/$', c.MovieCreate.as_view(), name='movie_add'),
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy as r


class Distributor(models.Model):
    distributor = models.CharField('distribuidor', max_length=50, unique=True)

    class Meta:
        ordering = ['distributor']
        verbose_name = 'distribuidor'
        verbose_name_plural = 'distribuidores'

    def __str__(self):
        return self.distributor


class Category(models.Model):
    category = models.CharField('categoria', max_length=50, unique=True)

    class Meta:
        ordering = ['category']
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.category


class Movie(models.Model):
    movie = models.CharField('filme', max_length=100)
    category = models.ForeignKey(
        'Category', verbose_name='categoria', related_name='movie_category')
    distributor = models.ForeignKey(
        'Distributor', verbose_name='distribuidor', related_name='movie_distributor')
    raised = models.DecimalField('arrecadou', max_digits=4, decimal_places=3)
    liked = models.BooleanField('gostou', default=True)
    release = models.DateTimeField(u'lançamento')

    class Meta:
        ordering = ['-release']
        verbose_name = 'filme'
        verbose_name_plural = 'filmes'

    def __str__(self):
        return self.movie

    def get_absolute_url(self):
        return r('core:movie_detail', kwargs={'pk': self.pk})

myproject/core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy as r
from django.views.generic import CreateView, ListView, DetailView
from django.db.models import Max
from .models import Movie


def home(request):
    return render(request, 'landpage.html')


class MovieList(ListView):
    template_name = 'core/movie_list.html'
    model = Movie
    context_object_name = 'movies'

    def get_queryset(self):
        m = Movie.objects.all()
        # Filme de maior bilheteria
        if self.request.GET.get('great_movie', False):
            q = Movie.objects.all().aggregate(Max('raised'))
            m = Movie.objects.filter(raised=q['raised__max'])
        return m


class MovieDetail(DetailView):
    template_name = 'core/movie_detail.html'
    model = Movie


class MovieCreate(CreateView):
    template_name = 'core/movie_form.html'
    model = Movie
    fields = '__all__'
    success_url = r('core:movie_list')

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">


    {% block title %}
      <title>Filmes</title>
    {% endblock title %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block css %}{% endblock css %}

    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 60px;
        padding-bottom: 40px;
        /*color: #5a5a5a;*/
      }
    </style>

  </head>
  <body id="page-top">

    {% block menu %}
      {% include "menu.html" %}
    {% endblock menu %}

    {% block content %}{% endblock content %}

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

myproject/core/templates/core/movie_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <ul class="breadcrumb">
        <li><a href="{% url 'core:movie_list' %}">Filmes</a> <span class="divider"></span></li>
        <li class="active">{{ movie.movie }}</li>
      </ul>

      <div class="col-sm-6 col-md-4">
        <div class="list-group">
          <h1>
            {{ movie.movie}}
            {% if movie.liked %}
              <td><span class="pull-right glyphicon glyphicon-ok-sign" style="color: #44AD41"></span></td>
            {% else %}
              <td><span class="pull-right glyphicon glyphicon-minus-sign" style="color: #DE2121"></span></td>
            {% endif %}
          </h1>
          <div class="list-group-item">
            <h4>{{ movie.category }}</h4>
          </div>
          <div class="list-group-item">
            <h4>{{ movie.distributor }}</h4>
          </div>
          <div class="list-group-item">
            <h3>U$ {{ movie.raised }}</h3>
          </div>
          <div class="list-group-item">
            <h4>{{ movie.release|date:"d/m/Y" }}</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

myproject/core/templates/core/movie_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block content %}

<div class="container">
  <form class="form-horizontal col-sm-10" action="." method="POST">
      <legend>Cadastrar</legend>
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}

    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <button type="submit" id="id_submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
  </form>
</div>

{% endblock content %}

myproject/core/templates/core/movie_list.html
{% extends "base.html" %}

{% block content %}

<div class="container">

  <div class="page-header">
      <a class="btn btn-primary pull-right" href="{% url 'core:movie_add' %}"><i class="glyphicon glyphicon-plus"></i> Adicionar filme</a>
    <h2><a href="?great_movie=1">Filme de maior bilheteria</a></h2>
  </div>

  {% if movies %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Filme</th>
          <th>Categoria</th>
          <th>Distribuidor</th>
          <th>Bilheteria (bilhões)</th>
          <th>Lançamento</th>
          <th>Gostou</th>
        </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
          <tr>
            <td><a href="{{ movie.get_absolute_url }}">{{ movie.movie }}</a></td>
            <td>{{ movie.category }}</td>
            <td>{{ movie.distributor }}</td>
            <td>U$ {{ movie.raised }}</td>
            <td>{{ movie.release|date:"d/m/Y" }}</td>
            {% if movie.liked %}
              <td><span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span></td>
            {% else %}
              <td><span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span></td>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Tutorial Django</h1>
      <h3>Bem-vindo ao Django!</h3>
    </div>
  </div>
{% endblock content %}

myproject/core/templates/landpage.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">


    <title>Filmes</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Filmes</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'core:movie_list' %}">Filmes</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="https://github.com/rg3915/tutoriais/tree/master/django-basic" target="_blank">GitHub</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Seus filmes favoritos estão aqui</h1>
                <hr>
                <p>Veja a lista dos seus filmes favoritos e descubra qual foi o filme de maior bilheteria de todos os tempos!</p>
                <a href="{% url 'core:movie_list' %}" class="btn btn-primary btn-xl page-scroll">Filmes aqui</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                    <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
                        <h3>Sturdy Templates</h3>
                        <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
                        <h3>Ready to Ship</h3>
                        <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">We update dependencies to keep things fresh.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
                        <h3>Made with Love</h3>
                        <p class="text-muted">You have to make your websites with love these days!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter popup-gallery">
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/01.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/01.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    Guardiões da Galáxia Vol. 2
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/02.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/02.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    Star Wars 7
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/03.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/03.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    Doutor Estranho
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/04.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/04.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    Avatar
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/05.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/05.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    The Matrix
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'img/portfolio/fullsize/06.jpg' %}" class="portfolio-box">
                        <img src="{% static 'img/portfolio/thumbnails/06.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <!-- Category -->
                                </div>
                                <div class="project-name">
                                    Titanic
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>

myproject/core/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'core:movie_list' %}"><span class="glyphicon glyphicon-film"></span> Filmes</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>